### ISSUE TITLE
Request: Biome toggle in config file

### ISSUE THREAD

**Issue by ghost** [alphawolf918/Zollern-Extras#1]
Even with brightness turned all the way up, I'm having problems seeing in the mushroom forest and I'd prefer to turn it off or lower it's weight significantly. To be fair, I can't see in nether fortresses either.
Thank you for the mod.

**Comment by alphawolf918** [comment]
Sounds more like an issue with your computer's brightness than with the mod, honestly. I can add in biome toggling at some point though, I don't see too big of an issue with doing that. However, you should know that in this next update, I'm adding something very big: it's a new dimension and it is (purposefully) very, very dark. So you might want to check your PC's settings at some point.

TL;DR: Yes I can do that, but it sounds more like your computer than my mod, and I'm adding a very, very dark new dimension soon, so you may want to check your settings.

Thank you for your input. Any feedback at all helps me out.

**Comment by ghost** [comment]
Thanks, I'll look for something more I can do at my end. It's a bit like not being able to see what's going on in videos when the cave's unlit.
